#requires -RunAsAdministrator
<#
.SYNOPSIS
  Turns a freshly-installed Eclipse Mosquitto Windows service into the
  mqtt-rbx broker: two listeners (1883 plain MQTT, 9001 MQTT-over-WebSockets).

.DESCRIPTION
  Default mode is anonymous - anyone on the LAN can connect, no username/
  password needed. Pass -Auth to lock it down instead: generates a random
  password per device account (RBX_esp01..RBX_espNN) plus a read-only
  RBX_dashboard account, with an ACL restricting each device to its own
  RBX/<name>/# subtree. Credentials from -Auth mode are never written into
  this repo - they're printed once and saved to
  %LOCALAPPDATA%\mqtt-rbx\credentials.txt on this machine only.

  Either way: rewrites mosquitto.conf (original backed up once, alongside),
  restarts the mosquitto service, and does a self-test publish.

.PARAMETER Auth
  Require username/password instead of the default anonymous access.

.PARAMETER Devices
  (-Auth only) how many device accounts to create. Default 4.

.PARAMETER NoDashboardUser
  (-Auth only) skip creating the read-only RBX_dashboard account.

.PARAMETER MosquittoDir
  Install directory. Default: the usual winget/installer location.

.EXAMPLE
  .\install-broker.ps1
  Anonymous access, simplest option - fine on a trusted home/classroom LAN.

.EXAMPLE
  .\install-broker.ps1 -Auth -Devices 4
  Username/password required, one account per device.
#>
param(
  [switch]$Auth,
  [int]$Devices = 4,
  [switch]$NoDashboardUser,
  [string]$MosquittoDir = "C:\Program Files\mosquitto"
)

$ErrorActionPreference = "Stop"

function New-RandomPassword {
  # 16 chars, alnum only - safe to pass around in shell one-liners and
  # mosquitto_pub -P without quoting headaches.
  $bytes = New-Object byte[] 24
  [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  ([Convert]::ToBase64String($bytes) -replace '[^a-zA-Z0-9]', '').Substring(0, 16)
}

if (-not (Test-Path $MosquittoDir)) {
  throw "Mosquitto not found at '$MosquittoDir'. Install it first: winget install --id EclipseFoundation.Mosquitto -e"
}

$mosquittoPub    = Join-Path $MosquittoDir "mosquitto_pub.exe"
$confPath        = Join-Path $MosquittoDir "mosquitto.conf"
$passwdPath      = Join-Path $MosquittoDir "rbx_passwd"
$aclPath         = Join-Path $MosquittoDir "rbx_acl.conf"
$dataDir         = Join-Path $MosquittoDir "data"
$logPath         = Join-Path $MosquittoDir "mosquitto.log"

if (-not (Test-Path $mosquittoPub)) {
  throw "Missing $mosquittoPub - is this a Mosquitto install directory?"
}
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

$accounts = [ordered]@{}

if ($Auth) {
  $mosquittoPasswd = Join-Path $MosquittoDir "mosquitto_passwd.exe"
  if (-not (Test-Path $mosquittoPasswd)) { throw "Missing $mosquittoPasswd" }

  # --- accounts ---------------------------------------------------------
  for ($i = 1; $i -le $Devices; $i++) {
    $name = "RBX_esp{0:D2}" -f $i
    $accounts[$name] = New-RandomPassword
  }
  if (-not $NoDashboardUser) {
    $accounts["RBX_dashboard"] = New-RandomPassword
  }

  # --- password file (mosquitto_passwd -b appends/updates one at a time) -
  if (Test-Path $passwdPath) { Remove-Item $passwdPath -Force }
  $first = $true
  foreach ($name in $accounts.Keys) {
    $pw = $accounts[$name]
    if ($first) {
      & $mosquittoPasswd -c -b $passwdPath $name $pw
      $first = $false
    } else {
      & $mosquittoPasswd -b $passwdPath $name $pw
    }
  }

  # --- ACL file: each device only touches its own subtree, dashboard is read-only
  $aclLines = @("# generated by install-broker.ps1 -Auth - do not hand-edit, rerun the script instead")
  foreach ($name in $accounts.Keys) {
    if ($name -eq "RBX_dashboard") {
      $aclLines += ""
      $aclLines += "user $name"
      $aclLines += "topic read RBX/#"
    } else {
      $aclLines += ""
      $aclLines += "user $name"
      $aclLines += "topic readwrite RBX/$name/#"
    }
  }
  Set-Content -Path $aclPath -Value $aclLines -Encoding ascii
} else {
  # Anonymous mode: remove any leftover auth files from a previous -Auth run
  # so a stale password_file/acl_file directive never lingers in mosquitto.conf.
  Remove-Item $passwdPath, $aclPath -Force -ErrorAction SilentlyContinue
}

# --- mosquitto.conf -----------------------------------------------------
if (Test-Path $confPath) {
  $backup = "$confPath.pre-rbx.bak"
  if (-not (Test-Path $backup)) { Copy-Item $confPath $backup }
}

$confLines = @(
  "# mqtt-rbx broker config - generated by install-broker.ps1"
  "# original config backed up to mosquitto.conf.pre-rbx.bak"
  ""
  "listener 1883"
  "protocol mqtt"
  ""
  "listener 9001"
  "protocol websockets"
  ""
)
if ($Auth) {
  $confLines += @(
    "allow_anonymous false"
    "password_file $passwdPath"
    "acl_file $aclPath"
    ""
  )
} else {
  $confLines += @(
    "allow_anonymous true"
    ""
  )
}
$confLines += @(
  "persistence true"
  "persistence_location $dataDir\"
  "log_dest file $logPath"
)
Set-Content -Path $confPath -Value $confLines -Encoding ascii

# --- restart service ------------------------------------------------------
Restart-Service -Name mosquitto -Force
Start-Sleep -Seconds 1
$svc = Get-Service -Name mosquitto
if ($svc.Status -ne "Running") { throw "mosquitto service did not come back up (status: $($svc.Status))" }

# --- self-test --------------------------------------------------------
$testTopic = "RBX/_selftest"
if ($Auth) {
  $testUser = $accounts.Keys | Select-Object -First 1
  $testPass = $accounts[$testUser]
  & $mosquittoPub -h 127.0.0.1 -p 1883 -u $testUser -P $testPass -t "RBX/$testUser/_selftest" -m "ok" 2>$null
} else {
  & $mosquittoPub -h 127.0.0.1 -p 1883 -t $testTopic -m "ok" 2>$null
}
if ($LASTEXITCODE -ne 0) { throw "self-test publish failed - check $logPath" }

$lanIp = (Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object { $_.InterfaceAlias -notmatch 'Loopback' -and $_.IPAddress -notmatch '^169\.254' } |
  Select-Object -First 1 -ExpandProperty IPAddress)

Write-Host ""
Write-Host "mqtt-rbx broker is up." -ForegroundColor Green
Write-Host "  host: $lanIp   ports: 1883 (mqtt) / 9001 (websockets)"

if ($Auth) {
  # --- save credentials locally (never in the repo) ------------------------
  $credDir = Join-Path $env:LOCALAPPDATA "mqtt-rbx"
  New-Item -ItemType Directory -Force -Path $credDir | Out-Null
  $credFile = Join-Path $credDir "credentials.txt"

  $out = @()
  $out += "# mqtt-rbx credentials - generated $(Get-Date -Format o)"
  $out += "# broker host (LAN IP): $lanIp"
  $out += "# ports: 1883 (mqtt), 9001 (websockets)"
  $out += ""
  foreach ($name in $accounts.Keys) { $out += "$name`t$($accounts[$name])" }
  Set-Content -Path $credFile -Value $out -Encoding ascii

  Write-Host "  auth: required"
  Write-Host ""
  Write-Host "Accounts (also saved to $credFile):"
  foreach ($name in $accounts.Keys) {
    Write-Host ("  {0,-16} {1}" -f $name, $accounts[$name])
  }
} else {
  Write-Host "  auth: none (anonymous) - anyone on this network can publish/subscribe"
  Write-Host ""
  Write-Host "Next: point each board's arduino_secrets.h at MQTT_HOST=$lanIp, no username/password needed," -ForegroundColor Yellow
  Write-Host "and open web\dashboard.html?host=$lanIp." -ForegroundColor Yellow
}
