#requires -RunAsAdministrator
<#
.SYNOPSIS
  Turns a freshly-installed Eclipse Mosquitto Windows service into the
  mqtt-rbx broker: two listeners (1883 plain MQTT, 9001 MQTT-over-WebSockets),
  username/password auth, a per-device ACL, and freshly generated passwords.

.DESCRIPTION
  - Generates a random password for each device account (RBX_esp01..RBX_espNN)
    and, unless -NoDashboardUser is passed, a read-only RBX_dashboard account.
  - Writes a Mosquitto password file and ACL file next to mosquitto.conf.
  - Rewrites mosquitto.conf (the original is backed up once, alongside).
  - Restarts the mosquitto service and does a self-test publish/subscribe.
  - Credentials are NEVER written into this repo. They're printed once and
    saved to %LOCALAPPDATA%\mqtt-rbx\credentials.txt on this machine only.

.PARAMETER Devices
  How many device accounts to create (RBX_esp01, RBX_esp02, ...). Default 4.

.PARAMETER NoDashboardUser
  Skip creating the read-only RBX_dashboard account.

.PARAMETER MosquittoDir
  Install directory. Default: the usual winget/installer location.

.EXAMPLE
  .\install-broker.ps1 -Devices 4
#>
param(
  [int]$Devices = 4,
  [switch]$NoDashboardUser,
  [string]$MosquittoDir = "C:\Program Files\mosquitto"
)

$ErrorActionPreference = "Stop"

function New-RandomPassword {
  # 16 chars, alnum only - safe to pass around in shell one-liners and
  # mosquitto_pub -P without quoting headaches.
  $bytes = New-Object byte[] 24
  [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  ([Convert]::ToBase64String($bytes) -replace '[^a-zA-Z0-9]', '').Substring(0, 16)
}

if (-not (Test-Path $MosquittoDir)) {
  throw "Mosquitto not found at '$MosquittoDir'. Install it first: winget install --id EclipseFoundation.Mosquitto -e"
}

$mosquittoPasswd = Join-Path $MosquittoDir "mosquitto_passwd.exe"
$mosquittoPub    = Join-Path $MosquittoDir "mosquitto_pub.exe"
$mosquittoSub    = Join-Path $MosquittoDir "mosquitto_sub.exe"
$confPath        = Join-Path $MosquittoDir "mosquitto.conf"
$passwdPath      = Join-Path $MosquittoDir "rbx_passwd"
$aclPath         = Join-Path $MosquittoDir "rbx_acl.conf"
$dataDir         = Join-Path $MosquittoDir "data"
$logPath         = Join-Path $MosquittoDir "mosquitto.log"

foreach ($exe in @($mosquittoPasswd, $mosquittoPub, $mosquittoSub)) {
  if (-not (Test-Path $exe)) { throw "Missing $exe - is this a Mosquitto install directory?" }
}
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

# --- accounts ---------------------------------------------------------
$accounts = [ordered]@{}
for ($i = 1; $i -le $Devices; $i++) {
  $name = "RBX_esp{0:D2}" -f $i
  $accounts[$name] = New-RandomPassword
}
if (-not $NoDashboardUser) {
  $accounts["RBX_dashboard"] = New-RandomPassword
}

# --- password file (mosquitto_passwd -b appends/updates one at a time) -
if (Test-Path $passwdPath) { Remove-Item $passwdPath -Force }
$first = $true
foreach ($name in $accounts.Keys) {
  $pw = $accounts[$name]
  if ($first) {
    & $mosquittoPasswd -c -b $passwdPath $name $pw
    $first = $false
  } else {
    & $mosquittoPasswd -b $passwdPath $name $pw
  }
}

# --- ACL file: each device only touches its own subtree, dashboard is read-only
$aclLines = @("# generated by install-broker.ps1 - do not hand-edit, rerun the script instead")
foreach ($name in $accounts.Keys) {
  if ($name -eq "RBX_dashboard") {
    $aclLines += ""
    $aclLines += "user $name"
    $aclLines += "topic read RBX/#"
  } else {
    $aclLines += ""
    $aclLines += "user $name"
    $aclLines += "topic readwrite RBX/$name/#"
  }
}
Set-Content -Path $aclPath -Value $aclLines -Encoding ascii

# --- mosquitto.conf -----------------------------------------------------
if (Test-Path $confPath) {
  $backup = "$confPath.pre-rbx.bak"
  if (-not (Test-Path $backup)) { Copy-Item $confPath $backup }
}

$confLines = @(
  "# mqtt-rbx broker config - generated by install-broker.ps1"
  "# original config backed up to mosquitto.conf.pre-rbx.bak"
  ""
  "listener 1883"
  "protocol mqtt"
  ""
  "listener 9001"
  "protocol websockets"
  ""
  "allow_anonymous false"
  "password_file $passwdPath"
  "acl_file $aclPath"
  ""
  "persistence true"
  "persistence_location $dataDir\"
  "log_dest file $logPath"
)
Set-Content -Path $confPath -Value $confLines -Encoding ascii

# --- restart service ------------------------------------------------------
Restart-Service -Name mosquitto -Force
Start-Sleep -Seconds 1
$svc = Get-Service -Name mosquitto
if ($svc.Status -ne "Running") { throw "mosquitto service did not come back up (status: $($svc.Status))" }

# --- self-test --------------------------------------------------------
$testUser = $accounts.Keys | Select-Object -First 1
$testPass = $accounts[$testUser]
$testTopic = "RBX/$testUser/_selftest"
& $mosquittoPub -h 127.0.0.1 -p 1883 -u $testUser -P $testPass -t $testTopic -m "ok" 2>$null
if ($LASTEXITCODE -ne 0) { throw "self-test publish failed - check $logPath" }

# --- save credentials locally (never in the repo) ------------------------
$credDir = Join-Path $env:LOCALAPPDATA "mqtt-rbx"
New-Item -ItemType Directory -Force -Path $credDir | Out-Null
$credFile = Join-Path $credDir "credentials.txt"
$lanIp = (Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object { $_.InterfaceAlias -notmatch 'Loopback' -and $_.IPAddress -notmatch '^169\.254' } |
  Select-Object -First 1 -ExpandProperty IPAddress)

$out = @()
$out += "# mqtt-rbx credentials - generated $(Get-Date -Format o)"
$out += "# broker host (LAN IP): $lanIp"
$out += "# ports: 1883 (mqtt), 9001 (websockets)"
$out += ""
foreach ($name in $accounts.Keys) { $out += "$name`t$($accounts[$name])" }
Set-Content -Path $credFile -Value $out -Encoding ascii

Write-Host ""
Write-Host "mqtt-rbx broker is up." -ForegroundColor Green
Write-Host "  host: $lanIp   ports: 1883 (mqtt) / 9001 (websockets)"
Write-Host ""
Write-Host "Accounts (also saved to $credFile):"
foreach ($name in $accounts.Keys) {
  Write-Host ("  {0,-16} {1}" -f $name, $accounts[$name])
}
Write-Host ""
Write-Host "Next: put a device's name/password into its arduino_secrets.h," -ForegroundColor Yellow
Write-Host "and open web\dashboard.html?host=$lanIp with the RBX_dashboard account." -ForegroundColor Yellow
